I have committed what is done and works.
BudaiS/Diploma_TestRail_Sergey_Budai pull request #1
Opened 2022-09-04 21:14 UTC by BudaiS

2022-09-05 08:10 UTC, voropa requested changes

2022-09-05 08:10 UTC, voropa commented on src/test/java/pages/AddNewProjectPage.java
> +        WebElement button = driver.findElement(By.cssSelector("input#suite_mode_single"));
Почему локаторы прямо в методах, а не вынесены на уровень атрибутов класса?

2022-09-05 08:10 UTC, voropa commented on src/test/java/pages/AddNewProjectPage.java
> +    @Override
Вы в каждом классе-наследнике переопределяете этот метод и используете тот же самый локатор IMAGE из base класа. Так какой смысо его переопределять? Осставьте его в base классе

2022-09-05 08:10 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    private final static By TEST_PROJECT = By.xpath("//div[contains(@class,'summary-title')]//following-sibling::a[text()='TestProject']");
Сдается мне, что 'TestProject' - это название проекта, которое вы захардкодили в локаторе. Сделаайте локатор динамическим, чтобы он примнимал название проекта в качестве аргумента

2022-09-05 08:10 UTC, voropa commented on src/test/java/tests/BaseTests.java
> +    protected String EMAIL = "budai.s@mail.ru";
Вынесите email/pass в .property файл

2022-09-15 18:56 UTC, voropa requested changes

2022-09-15 18:56 UTC, voropa commented on src/test/java/elements/DropDown.java
> +        if (Objects.nonNull(visibleText)) {
Зачем 2 подряд  проверки на null? Одной достаточно в самом начале

2022-09-15 18:56 UTC, voropa commented on src/test/java/elements/Input.java
> +            System.out.printf("Settings %s input value = %s", label, value);
Замените все System.out на log4j, если хотите что-то логировать

2022-09-15 18:56 UTC, voropa commented on src/test/java/models/TestCase.java
> +    private String title;                   //elements = Input, label = "Title"
Зачем эти коментарии?

2022-09-15 19:27 UTC, BudaiS commented on src/test/java/models/TestCase.java
> +    private String title;                   //elements = Input, label = "Title"
для удобства потом заполнения fillForm.

2022-09-15 19:55 UTC, voropa requested changes

2022-09-15 19:55 UTC, voropa commented on src/test/java/pages/testRunsResult/AddTestPlanPage.java
> +        new AddTestPlanPage(driver).nameSetValue(inputTestPlan.getName());
Зачем вы внутри метода страаницы создаете экземпляр класса этой же страницы?) Это циклическая звисомость получается) Чтобы вызвать этот метод, можно  прост онаписать this.nameSetValue()

2022-09-16 19:49 UTC, voropa requested changes
Избегайте логирования статического контента, в этом нет смысла. Логируйте динамический текст, который включает в себя значение аргументов, с которыми была вызвана функция и т.д. То же самое про allure @Steps

2022-09-16 19:49 UTC, voropa commented on src/test/java/elements/DropDown.java
> +            log.debug(String.format("Scroll to dropdown %s", label));
Вместо того, чтобы перед каждым вызовом метрда scrollIntiView писать лог, можно написать его внутри самого метода scrollIntiView

2022-09-16 19:49 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    @Step("wait for page loaded")
От этих логов нет ниикакого смысла, потому что в них статический текст и непонятно какую страницу ждет

2022-09-16 19:49 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("click 'TestProject'")
В степах allure можно тоже передавать динамически значения входного аргумента функции, чтобы не хардкодить: @Step("click {projectName}")

2022-09-16 19:49 UTC, voropa commented on src/test/java/utils/TestListener.java
> +        System.out.println("Test " + result.getName() + " failed");
Почему тут System.out, а не log.debug?

2022-09-16 19:49 UTC, voropa commented on src/test/java/utils/TestListener.java
> +    @Attachment
Кажется тут не хватает параметров у этой аннотации @Attachment

2022-09-19 11:32 UTC, voropa commented on src/test/java/elements/DropDown.java
> +            log.debug(String.format("Scroll to dropdown %s", label));
Этот коментарий по-прежнему валиден

2022-09-19 19:17 UTC, voropa approved these changes

2022-09-19 20:26 UTC, merged